version: "3"
services:

  php:
    build: ./docker/the-moon-php
    container_name: the-moon-php
    ports:
      - 5173:5173
    volumes:
      - ./src/the-moon-php:/var/www/the-moon-php
      - ./docker/the-moon-php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/the-moon-php

  python:
    build:
      context: ./docker/the-moon-python
      dockerfile: Dockerfile
    container_name: the-moon-python
    volumes:
      - ./src/the-moon-python:/var/www/src/the-moon-python
    working_dir: /var/www/src/python
    ports:
      - "5000:5000"
    environment:
      - >
        PYTHONPATH=/var/www/src/the-moon-python:/var/www/src/the-moon-python/Repository:/var/www/src/the-moon-python/Service:/var/www/src/the-moon-python/Util:/var/www/src/the-moon-python/Class:/var/www/src/the-moon-python/Tests:/var/www/src/the-moon-python/DataTransferObject:${PYTHONPATH}


  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    ports:
      - 80:80
      - 8000:8000
      - 8001:8001
    volumes:
      - ./src/the-moon-php:/var/www/the-moon-php
      - ./src/the-moon-python:/var/www/the-moon-python      
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Tokyo

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
    depends_on:
      - php
    shm_size: '2gb' 

volumes:
  mysql:
